name: Main Actions Playbox

on:
  push:
    branches: [main]

jobs:
  # run-nested-npm-script:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2.4.2

  #     - name: Enter src and run list-folder
  #       run: |
  #         cd src/
  #         npm run list-folder

  create-new-file:
    name: Create new file in src
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create file
        run: touch src/dependent.js

  list-src:
    name: List src folder using npm script
    runs-on: ubuntu-latest
    needs: [create-new-file]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List src folder
        run: |
          cd src/
          npm run list-folder
