name: Main Actions Playbox

on:
  push:
    branches: [main]

jobs:
  run-nested-npm-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - run: |
          cd src/
          npm run list-folder
